### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by zloyreznic** [jcbvm/ember-i18n-editor#12]
Please add default language
I have 3 langs
en ro ru
If I add new key to lang ro he dont apear.

**Comment by jcbvm** [comment]
What exactly do you mean with a default language?

Can you describe the steps you are doing or showing some screenshots of the problem you have? Adding a key will add it to all languages you have open in the editor, afterwards it will only save the key to the language files when a value is filled in for that language and key.

**Comment by zloyreznic** [comment]
if you add new key manualy on file he work!
sorry all is ok :+1:
