### ISSUE TITLE
Add option to save localization files using line breaks

### ISSUE THREAD

**Issue by splattne** [jcbvm/ember-i18n-editor#2]
If the tool is used by multiple team members on the same project, it will inevitably come to some merge issues because of missing line breaks in the resulting files. It also would help to see which changes were made if the JSON isn't just a long, single line.

Could you introduce an option for formatting the resulting JSON/ES6?

Thanks for this tool, btw – it really is a great help in localizing big applications!

**Comment by jcbvm** [comment]
That's a good point indeed. I can add a option for pretty printing so the json will look like an object structure in which you can clearly see the differences when merging. Minifying the result can than be done by an external tool or with ember-cli for example.

**Comment by jcbvm** [comment]
Version 0.5.0 now introduces a new menu item "Settings" where you can enabled/disable minification of the output. 

By default it will NOT minify the output anymore when saving. So for your files to be changed, just edit a translation and save it. 

The minify setting will be remembered when closing and reopening the editor.

**Comment by splattne** [comment]
Awesome, works like a charm! Thanks for the quick response.
