### ISSUE TITLE
Support to languages

### ISSUE THREAD

**Issue by edelciomolina** [jcbvm/ember-i18n-editor#8]
@jcbvm If you to implement option to multiples languages I will have pleasure to contribuited the translation to portuguese. Unfortunatelly I do not have experience with Java, but if you start I can help you.

**Comment by jcbvm** [comment]
There already is support for multi language, currently only dutch and english are supported (it determines your languages by the system language you are using). 

You can create a PR or send me a translation file for portuguese. Take a look at https://github.com/jcbvm/ember-i18n-editor/blob/master/src/main/resources/bundles/messages.properties. These are the english translations which then need to be translated to portuguese.

**Comment by edelciomolina** [comment]
Done! Patch sent, https://github.com/edelciomolina/ember-i18n-editor/commit/7c68b4b4c1087ffe7eab807ca75752a6b276096b

@jcbvm When you can, release a new version of executables with latest commits. Thank you!

**Comment by jcbvm** [comment]
Thanks, will create a new release when ready, should be somewhere this week.

**Comment by jcbvm** [comment]
I added three new translations:

    dialogs.translation.conflict.text.replace = There already exists a translation with this key, do you want to replace it?
    dialogs.translation.conflict.text.merge = There already exists a translation with this key, do you want to merge it?
    dialogs.translation.conflict.title = Translation conflict

Can you pull these changes in your fork and add the portuguese translations for them?
Afterwards you can create a pull request in this branch, so I can merge your translations :).

**Comment by edelciomolina** [comment]
Done!
https://github.com/jcbvm/ember-i18n-editor/pull/9

**Comment by jcbvm** [comment]
@edelciomolina In a new version I'm preparing I've added a introduction text when the program is opened for the first time. May I ask you what the correct portuguese translation is for:
"Drop a folder here or go to File > Open Folder... to start"
